name = "Midnight"
license = "MIT"
licenselink = "https://git.shadow53.com/BluestNight/Midnight/src/branch/master/LICENSE.md"
description = "A modern Hugo theme with lots of configuration options to make it truly yours. Supports custom plugins to integrate your own features into the theme."
homepage = "https://bluestnight.com/products/midnight"
min_version = 0.48
tags = [
    "Blog",
    "Clean",
    "Creative",
    "Custom Colors",
    "Dark",
    "Extensible",
    "Mobile Friendly",
    "Netlify",
    "Plugins",
    "Widgets",
    "Writing"
]
features = [
    "Contact Form",
    "Error Validation",
    "Extensible",
    "Font Awesome",
    "HTTP/2",
    "Plugins",
    "Print CSS",
    "Responsive",
    "Search",
    "Syntax Highlighting",
]

[author]
  name = "Michael Bryant"
  homepage = "https://shadow53.com"
